
export class Product {
  constructor(id, title, description, price, image, featured) {
    this.id = id;
    this.title = title;
    this.descripcion = description;
    this.price = price;
    this.image = image;
    this.featured = featured;
  }

  applyDiscount(percentage) {
    return this.price - (this.price * percentage / 100);
  }
}

export const products = [
  new Product(1, "Zapatillas Nike Run Swift 3", "Diseñadas para quienes buscan comodidad y rendimiento diario, las Nike Run Swift 3 combinan una amortiguación suave con una estructura liviana y transpirable. Su malla superior mejora la ventilación durante carreras intensas, mientras que la entresuela de espuma proporciona una pisada suave y reactiva. Ideales para entrenamientos o caminatas urbanas, su suela de goma ofrece tracción duradera sobre diversas superficies.", 149999, "./assets/images/products/product01", false),
  new Product(2, "Zapatillas Adidas Ultraboost 5", "Las Adidas Ultraboost 5 ofrecen una combinación ideal de estilo, innovación y rendimiento. Con su tecnología Boost de última generación, brindan una amortiguación reactiva en cada paso. El tejido Primeknit superior se adapta al pie como un guante, garantizando soporte y comodidad. Perfectas para correr largas distancias o para el uso urbano diario, destacan por su diseño moderno y sujeción óptima.", 229999, "./assets/images/products/product02", false),
  new Product(3, "Zapatillas Run 60s 4.0", "Inspiradas en el estilo retro del running, las Adidas Run 60s 4.0 combinan diseño clásico con comodidad moderna. Cuentan con una parte superior de malla y cuero sintético que brinda transpirabilidad y soporte, mientras que la entresuela acolchada garantiza una pisada suave. Ideales para el uso diario, estas zapatillas son versátiles, livianas y siempre a la moda.", 89999, "./assets/images/products/product03", true),
  new Product(4, "Zapatillas Puma RS-X Parachute Landing", "Con un diseño audaz y futurista, las RS-X Parachute Landing destacan por su combinación de materiales técnicos y detalles gráficos llamativos. Su estructura robusta ofrece soporte y durabilidad, mientras que la entresuela proporciona una amortiguación cómoda para el uso diario. Perfectas para quienes buscan un estilo urbano único sin sacrificar confort.", 89999, "./assets/images/products/product04", false),
  new Product(5, "Zapatillas Nike Revolution 7", "Diseñadas para ofrecer una experiencia de carrera cómoda y accesible, las Nike Revolution 7 cuentan con una entresuela de espuma ligera que brinda amortiguación y soporte en cada pisada. Su parte superior de malla transpirable mantiene el pie fresco, mientras que la suela de goma ofrece tracción duradera para uso diario y entrenamientos. Perfectas para quienes buscan rendimiento y estilo en un diseño sencillo y funcional.", 99999, "./assets/images/products/product05", false),
  new Product(6, "Zapatillas Adidas Duramo SL2", "Las Adidas Duramo SL2 combinan ligereza y comodidad para acompañarte en cada entrenamiento. Su parte superior de malla transpirable ofrece ventilación óptima, mientras que la entresuela de EVA proporciona amortiguación y soporte durante la carrera o el uso diario. Con una suela de goma resistente, garantizan tracción y durabilidad en diversas superficies. Perfectas para quienes buscan rendimiento y estilo minimalista.", 99999, "./assets/images/products/product06", false),
  new Product(7, "Zapatillas Nike Revolution 7", "Diseñadas para ofrecer una experiencia de carrera cómoda y accesible, las Nike Revolution 7 cuentan con una entresuela de espuma ligera que brinda amortiguación y soporte en cada pisada. Su parte superior de malla transpirable mantiene el pie fresco, mientras que la suela de goma ofrece tracción duradera para uso diario y entrenamientos. Perfectas para quienes buscan rendimiento y estilo en un diseño sencillo y funcional.", 99999, "./assets/images/products/product07", false),
  new Product(8, "Zapatillas Nike Downshifter 13", "Diseñadas para ofrecer ligereza y comodidad en cada paso, las Nike Downshifter 13 cuentan con una parte superior de malla transpirable que mantiene los pies frescos durante el entrenamiento. Su entresuela de espuma brinda una amortiguación suave y reactiva, mientras que la suela de goma flexible garantiza tracción y durabilidad en distintas superficies. Ideales para corredores y para el uso diario.", 119999, "./assets/images/products/product08", false),
  new Product(9, "Zapatillas Adidas Grand Court Alpha 00s", "Con un diseño inspirado en el estilo clásico de los años 2000, las Adidas Grand Court Alpha 00s combinan elegancia y confort para un look retro renovado. Su parte superior de cuero sintético aporta durabilidad y un acabado pulido, mientras que la entresuela acolchada ofrece una amortiguación ligera para uso diario. Perfectas para quienes buscan un calzado versátil con estilo vintage.", 119999, "./assets/images/products/product09", true),
  new Product(10, "Zapatillas Nike Air Max SC", "Las Nike Air Max SC combinan un diseño moderno con la icónica amortiguación Air Max para brindar comodidad y estilo en cada paso. Su parte superior de malla y materiales sintéticos ofrece transpirabilidad y soporte, mientras que la unidad Air visible en el talón proporciona una amortiguación reactiva y protección contra impactos. Ideales para el uso diario y entrenamientos ligeros.", 169999, "./assets/images/products/product10", false),
  new Product(11, "Zapatillas Adidas Tensaur Sport 2.0 Kids", "Diseñadas especialmente para los más chicos, las Adidas Tensaur Sport 2.0 Kids ofrecen comodidad y soporte durante sus actividades diarias. Cuentan con una parte superior de malla transpirable que mantiene los pies frescos y una entresuela acolchada que brinda amortiguación ligera. Su suela de goma duradera garantiza tracción segura en diversas superficies. Perfectas para acompañar el ritmo activo de los niños con estilo y funcionalidad.", 69999, "./assets/images/products/product11", true),
  new Product(12, "Zapatillas Adidas VL Court Mercedes - AMG Petronas F1 team", "Diseñadas en colaboración con el equipo Mercedes-AMG Petronas de Fórmula 1, estas zapatillas combinan estilo deportivo y alto rendimiento. Su parte superior de cuero sintético y malla ofrece durabilidad y ventilación, mientras que la entresuela proporciona una amortiguación ligera para comodidad durante todo el día. Con detalles exclusivos del equipo F1, son perfectas para los fanáticos que buscan un look urbano con identidad racing.", 119999, "./assets/images/products/product12", false),
  new Product(13, "Zapatillas Hoka Clifton 8", "Las Hoka Clifton 8 ofrecen una amortiguación superior y un diseño ultraligero, ideales para corredores que buscan comodidad en largas distancias. Su parte superior de malla técnica mejora la ventilación, mientras que la entresuela de espuma EVA brinda una pisada suave y reactiva. Además, su suela con tecnología de tracción avanzada garantiza estabilidad y durabilidad en diversos terrenos. Perfectas para entrenamiento y competición.", 189999, "./assets/images/products/product13", false),
  new Product(14, "Zapatillas Adidas Adizero SL2", "Diseñadas para velocidad y rendimiento, las Adidas Adizero SL2 combinan una construcción ultraligera con una respuesta dinámica en cada pisada. Su parte superior de malla transpirable ofrece soporte y ventilación, mientras que la entresuela proporciona amortiguación reactiva para acelerar con comodidad. La suela exterior de goma garantiza tracción y durabilidad, ideales para corredores que buscan máximo rendimiento.", 179999, "./assets/images/products/product14", false),
  new Product(15, "Zapatillas Nike Full Force Low", "Diseñadas para un estilo urbano y deportivo, las Nike Full Force Low combinan una construcción resistente con detalles modernos. Su parte superior de cuero y materiales sintéticos ofrece durabilidad y soporte, mientras que la entresuela acolchada brinda comodidad durante todo el día. Con una suela de goma que proporciona tracción fiable, son ideales para el uso diario y actividades casuales con un toque de estilo.", 139900, "./assets/images/products/product15", false),
  new Product(16, "Zapatillas Nike Flex Experience RN 12", "Las Nike Flex Experience RN 12 están diseñadas para brindar una sensación natural y flexible durante tus entrenamientos. Su parte superior de malla transpirable mantiene tus pies frescos, mientras que la entresuela con tecnología React ofrece una amortiguación suave y reactiva. Además, la suela exterior flexible proporciona una excelente tracción y libertad de movimiento. Perfectas para corredores que buscan comodidad y dinamismo en cada paso.", 129999, "./assets/images/products/product16", false)
];

